services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: crawler_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - POSTGRES_HOST=postgres
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    command: tail -f /dev/null

  airflow:
    image: apache/airflow:2.10.2-python3.12
    container_name: airflow-standalone
    user: "airflow"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=fb67749239a1234567890abcdef123456
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - POSTGRES_HOST=postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - ./app:/opt/airflow/app
    ports:
      - "8080:8080"
    command: standalone
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
