services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    # ports:
    #   - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: crawler_app
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    command: tail -f /dev/null

volumes:
  mongo_data:
