services:
  worker:
    profiles: 
      - worker
    build:
      context: ..
      dockerfile: docker/app/Dockerfile
    image: crawler/worker:latest
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED}
    working_dir: /app
    tty: true
    stdin_open: true

volumes:
  mongodb_data:
