services:
  proxy:
    profiles:
      - airflow  
    image: traefik:v3.6
    ports:
      - "8000:8000"       # HTTP 진입점
      - "8080:8080"   # Traefik 대시보드
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:8000"
    # environment:
    #   - DOCKER_API_VERSION=1.41
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    healthcheck:
      test: ["CMD", "wget", "--no-vertices", "--quiet", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
