services:
  proxy:
    image: traefik:v3.6
    restart: always
    ports:
      - "80:80"
    networks:
      - airflow-net
    depends_on:
      airflow:
        condition: service_healthy
      pgadmin:
        condition: service_healthy
      mongo-express:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik_dash.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      - "traefik.http.routers.traefik_dash.service=api@internal"
      - "traefik.http.routers.traefik_dash.entrypoints=web"
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--ping=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  airflow-net:
    external: true
