services:
  proxy:
    profiles:
      - airflow
    build:
      context: proxy
      dockerfile: Dockerfile
    image: crawler/proxy:latest
    ports:
      - "80:80"
    networks:
      - airflow-net
    depends_on:
      airflow:
        condition: service_started
      pgadmin:
        condition: service_started
      mongo-express:
        condition: service_started

networks:
  airflow-net:
    driver: bridge
