services:
  worker:
    profiles: 
      - worker
    build:
      context: ..
      dockerfile: docker/app/Dockerfile
    image: crawler/worker:latest
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - POSTGRES_HOST=postgres
      - PYTHONUNBUFFERED=1
    working_dir: /app
    tty: true
    stdin_open: true
    networks:
      - airflow-net

networks:
  airflow-net:
    driver: bridge

volumes:
  mongodb_data:
