
services:
  control-plane:
    build:
      context: ../services/kind
      dockerfile: Dockerfile
      args:
        - K8S_VERSION=v1.35.1
    image: local/kind:v1.35.1
    privileged: true
    hostname: control-plane
    environment:
      - DOCKER_TLS_CERTDIR= # DinD 사용 시 인증서 충돌 방지
    volumes:
      - ssh_keys:/root/.ssh:rw
      - /lib/modules:/lib/modules:ro
      - /home/ejpark/workspace/crawler/docker/services/kind/init.sh:/init.sh
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    healthcheck:
      # test: ["CMD", "kubectl", "cluster-info", "--kubeconfig=/etc/kubernetes/admin.conf"]
      test: ["CMD", "crictl", "info"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  worker:
    build:
      context: ../services/kind
      dockerfile: Dockerfile
      args:
        - K8S_VERSION=v1.35.1
    image: local/kind:v1.35.1
    privileged: true
    deploy:
      replicas: 1
    environment:
      - DOCKER_TLS_CERTDIR=       
    volumes:
      - ssh_keys:/root/.ssh:rw
      - /lib/modules:/lib/modules:ro
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    depends_on:
      control-plane:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "crictl", "info"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  ssh_keys:
